python3 manage.py makemigrations authuser
python3 manage.py makemigrations cargo_types
python3 manage.py makemigrations categories
python3 manage.py makemigrations dispatch
python3 manage.py makemigrations kyc
python3 manage.py makemigrations orders
python3 manage.py makemigrations payments
python3 manage.py makemigrations products
python3 manage.py makemigrations tasks
