# Generated by Django 4.2.1 on 2023-07-20 11:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Dispatch',
                'verbose_name_plural': 'Dispatch',
            },
        ),
    ]
