# Generated by Django 4.2.1 on 2023-07-20 11:36

import authuser.models.user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(error_messages='Email Already Taken', max_length=254, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_token_verified', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, max_length=300, null=True)),
                ('token_pin_id', models.CharField(blank=True, max_length=300, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('key', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.CharField(blank=True, max_length=600, null=True)),
                ('encoded', models.CharField(blank=True, max_length=600, null=True)),
                ('encrypt_date', models.DateField(default=django.utils.timezone.now)),
                ('rsa_duration', models.IntegerField(default=24)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'AuthUser',
                'verbose_name_plural': 'AuthUsers',
            },
            managers=[
                ('objects', authuser.models.user.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('authuser.customuser',),
            managers=[
                ('objects', authuser.models.user.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=50)),
                ('address', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('authuser.customuser',),
            managers=[
                ('objects', authuser.models.user.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('address', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('authuser.customuser',),
            managers=[
                ('objects', authuser.models.user.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('address', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('authuser.customuser',),
            managers=[
                ('objects', authuser.models.user.CustomUserManager()),
            ],
        ),
    ]
