# Generated by Django 4.2.2 on 2023-06-16 14:55

import authuser.models.user
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(error_messages='Email Already Taken', max_length=254, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=200)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('account_type', models.CharField(choices=[('vendor', 'Vendor'), ('agent', 'Agent'), ('driver', 'Driver'), ('users', 'users')], default='users', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_token_verified', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, max_length=300, null=True)),
                ('token_pin_id', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('key', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.CharField(blank=True, max_length=600, null=True)),
                ('encoded', models.CharField(blank=True, max_length=600, null=True)),
                ('encrypt_date', models.DateField(default=django.utils.timezone.now)),
                ('rsa_duration', models.IntegerField(default=24)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', authuser.models.user.CustomUserManager()),
            ],
        ),
    ]
