# Generated by Django 4.2.1 on 2023-07-11 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo_types', '0001_initial'),
        ('core', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('corebasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.corebasemodel')),
                ('cargo_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_type', to='cargo_types.cargotype')),
                ('order_id', models.ManyToManyField(related_name='orders', to='orders.order')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
            bases=('core.corebasemodel',),
        ),
    ]
