# Generated by Django 4.2.1 on 2023-07-18 16:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo_types', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cargo_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_type', to='cargo_types.cargotype')),
                ('order_id', models.ManyToManyField(related_name='orders', to='orders.order')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
