# Generated by Django 4.2.2 on 2023-06-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category_id_alter_product_user_id'),
        ('orders', '0002_alter_order_product_id_alter_order_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.ManyToManyField(related_name='products', to='products.product'),
        ),
    ]
